### PR TITLE
Add support for exploding graphics files

### PR DESCRIPTION
**Pull request by stephenmk**
The `audio` module already worked with graphics files as well, so I just renamed it to `media`.

I've tested this with DAIJIRIN2, DAIJISEN2, and NDS, and it seems to work fine.

### CODE REVIEW

**Comment by golddranks** [comment]
Thanks!! I'll look into this next Sunday!

**Comment by Jimmy-Z** [comment]
May I ask why is this not merged?

If the reason is the code quality (like using a String where an enum would be more appropriate), I might be able to help.

If it's for something else, please elaborate.

I'd like to help but really don't want to maintain a fork if possible.

**Comment by golddranks** [comment]
It's not merged because I haven't had the time to review it.

**Comment by Jimmy-Z** [comment]
That's ... something I can't help with 🤣

**Comment by golddranks** [comment]
I've already broke multiple promises to look into this or develop this project further. It will happen, but no promises about the schedule. Meanwhile, feel free to fork. (I'm not planning to abandon this, so you don't have to maintain a fork forever.)

**Comment by Jimmy-Z** [comment]
I read some of your code, and now I have some more questions:

* this commit https://github.com/golddranks/monokakido/pull/4/commits/3a0e0d2ea7779de4c2c549bce6e0eb3d3219e4f0
  prevented the media resource from creation if there was no index, as like SANKOKU8's case, the graphics dir is just a bunch of plain files, I guess this is ok for explosions, but for this lib in general, we should probably allow that, and implement `get` for plain files, am I right? and I guess get_by_idx won't work in this case anyway.

* `DictJson.contents` is a Vec, which reflects the actual JSON scheme, but in the end, only the last entry is used: https://github.com/golddranks/monokakido/blob/5ec9bd59ecd3836ac6fa81becd4401453f238310/src/dict.rs#L131 this is mostly true but not in all cases, like 中日辞典 and 日中辞典 from 小学館 is sold as a pack called 中日・日中辞典(CJ3).

* the file header magic check https://github.com/golddranks/monokakido/blob/5ec9bd59ecd3836ac6fa81becd4401453f238310/src/key.rs#L36 fails for me on SANKOKU8 since magic3 is not 0, this is strange since @stephenmk had it supported and I did not see him removing this check. Well I should probably ask him instead, maybe he had a different set of files.
update: @stephenmk explained this: https://github.com/stephenmk/monokakido/commit/3a0e0d2ea7779de4c2c549bce6e0eb3d3219e4f0#commitcomment-122083405

* the base path is hardcoded https://github.com/golddranks/monokakido/blob/5ec9bd59ecd3836ac6fa81becd4401453f238310/src/dict.rs#L38 as a lib I think we should probably let the caller decide, this should just be default for mac.

Afterthought: some of these should probably be new issues instead of hijacking this thread.

**Comment by stephenmk** [comment]
The functionality implemented by this pull request has now been implemented better by @Jimmy-Z in [mkd-utils](https://github.com/Jimmy-Z/mkd-utils), so I'm going to go ahead and close this PR and delete my fork.

**Pull request closed without merging**
